name: CI
on:
  - push
jobs:
  build:
    name: Code Quality
    timeout: 15
    runsOn: ubuntu-latest
    env:
      DO_NOT_TRACK: "1"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetchDepth: 2
          lfs: true
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          nodeVersion: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Code Quality Checks
        run: pnpm turbo format lint check-types test
